#!/usr/bin/env python3
"""Index local testcase artifacts generated by requirement testcase flows.

The script is read-only. It records file paths, inferred requirement names,
artifact types, row counts, columns, and companion files. It does not print CSV
row contents, requirement text, tokens, URLs, or server addresses.
"""

from __future__ import annotations

import argparse
import csv
import json
import re
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


DATE_RE = re.compile(r"(20\d{6})")
CSV_SUFFIXES = (
    ("_测试用例_AI检查_", "ai_checked_cases"),
    ("_测试用例_AI复扫_", "ai_rescan_cases"),
    ("_测试用例_", "main_cases"),
    ("_待确认用例_", "pending_cases"),
)
REPORT_SUFFIXES = (
    ("_覆盖报告_", "coverage_report"),
)
EXCLUDE_NAME_HINTS = (
    "埋点",
    "Bug驱动上线",
    "上线冒烟",
)
DEFAULT_EXCLUDES = {
    "node_modules",
    "Library",
    "Temp",
    "Build",
    "Logs",
    ".git",
    ".idea",
    ".vscode",
    "DerivedData",
    "obj",
    "bin",
    "dist",
}


@dataclass
class Artifact:
    path: str
    artifact_type: str
    date: str | None
    rows: int | None = None
    columns: list[str] = field(default_factory=list)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Read-only index of local requirement testcase CSV/report artifacts"
    )
    parser.add_argument(
        "roots",
        nargs="*",
        default=["."],
        help="Roots to scan. Defaults to current directory.",
    )
    parser.add_argument(
        "--include-other-flows",
        action="store_true",
        help="Include likely non-requirement flows such as tracking, bug-driven smoke, and RC artifacts.",
    )
    parser.add_argument(
        "--exclude-dir",
        action="append",
        default=[],
        help="Directory basename to skip. Can be repeated.",
    )
    parser.add_argument("--json", help="Write JSON summary to this path.")
    parser.add_argument("--csv", help="Write grouped CSV summary to this path.")
    parser.add_argument(
        "--print-paths",
        action="store_true",
        help="Print artifact paths in the text summary.",
    )
    return parser.parse_args()


def should_skip(path: Path, exclude_dirs: set[str]) -> bool:
    return any(part in exclude_dirs for part in path.parts)


def infer_type_and_name(path: Path) -> tuple[str, str] | None:
    stem = path.stem
    for marker, artifact_type in CSV_SUFFIXES + REPORT_SUFFIXES:
        if marker in stem:
            name = stem.split(marker, 1)[0]
            return artifact_type, name
    return None


def date_from_name(path: Path) -> str | None:
    match = DATE_RE.search(path.stem)
    return match.group(1) if match else None


def is_other_flow(path: Path, requirement_name: str) -> bool:
    text = f"{path.name} {requirement_name}"
    return any(hint in text for hint in EXCLUDE_NAME_HINTS)


def read_csv_meta(path: Path) -> tuple[int, list[str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.reader(f)
        try:
            columns = next(reader)
        except StopIteration:
            return 0, []
        rows = sum(1 for _ in reader)
    return rows, columns


def iter_candidate_files(roots: list[Path], exclude_dirs: set[str]):
    for root in roots:
        if not root.exists():
            continue
        if root.is_file():
            yield root
            continue
        for path in root.rglob("*"):
            if should_skip(path, exclude_dirs):
                continue
            if not path.is_file():
                continue
            if path.suffix.lower() not in {".csv", ".md", ".txt"}:
                continue
            if "测试用例" in path.name or "待确认用例" in path.name or "覆盖报告" in path.name:
                yield path


def project_label(path: Path) -> str:
    parts = list(path.parts)
    if "moby" in parts:
        idx = parts.index("moby")
        if idx + 1 < len(parts):
            return parts[idx + 1]
    if "Desktop" in parts:
        idx = parts.index("Desktop")
        if idx + 1 < len(parts):
            return parts[idx + 1]
    return path.parent.name


def build_index(args: argparse.Namespace) -> dict[str, Any]:
    exclude_dirs = DEFAULT_EXCLUDES | set(args.exclude_dir)
    roots = [Path(root).expanduser().resolve() for root in args.roots]
    groups: dict[str, dict[str, Any]] = {}
    skipped_other_flows = 0

    for path in iter_candidate_files(roots, exclude_dirs):
        inferred = infer_type_and_name(path)
        if not inferred:
            continue
        artifact_type, requirement_name = inferred
        if not args.include_other_flows and is_other_flow(path, requirement_name):
            skipped_other_flows += 1
            continue

        key = f"{project_label(path)}::{requirement_name}"
        group = groups.setdefault(
            key,
            {
                "project": project_label(path),
                "requirement_name": requirement_name,
                "dates": set(),
                "artifacts": [],
                "main_case_rows": 0,
                "pending_case_rows": 0,
                "ai_checked_case_rows": 0,
                "has_ai_checked": False,
                "has_coverage_report": False,
            },
        )
        date = date_from_name(path)
        if date:
            group["dates"].add(date)
        rows = None
        columns: list[str] = []
        if path.suffix.lower() == ".csv":
            try:
                rows, columns = read_csv_meta(path)
            except UnicodeDecodeError:
                rows, columns = read_csv_meta(path)
        artifact = Artifact(
            path=str(path),
            artifact_type=artifact_type,
            date=date,
            rows=rows,
            columns=columns,
        )
        group["artifacts"].append(artifact)
        if artifact_type == "main_cases":
            group["main_case_rows"] += rows or 0
        elif artifact_type == "pending_cases":
            group["pending_case_rows"] += rows or 0
        elif artifact_type in {"ai_checked_cases", "ai_rescan_cases"}:
            group["ai_checked_case_rows"] += rows or 0
            group["has_ai_checked"] = True
        elif artifact_type == "coverage_report":
            group["has_coverage_report"] = True

    serializable_groups = []
    for group in groups.values():
        artifacts: list[Artifact] = group.pop("artifacts")
        group["dates"] = sorted(group["dates"])
        group["artifact_count"] = len(artifacts)
        group["artifact_types"] = sorted({artifact.artifact_type for artifact in artifacts})
        group["artifacts"] = [
            {
                "path": artifact.path,
                "artifact_type": artifact.artifact_type,
                "date": artifact.date,
                "rows": artifact.rows,
                "columns": artifact.columns,
            }
            for artifact in sorted(artifacts, key=lambda a: (a.artifact_type, a.path))
        ]
        serializable_groups.append(group)

    serializable_groups.sort(key=lambda g: (g["project"], g["requirement_name"]))
    summary = {
        "roots": [str(root) for root in roots],
        "group_count": len(serializable_groups),
        "project_count": len({g["project"] for g in serializable_groups}),
        "artifact_count": sum(g["artifact_count"] for g in serializable_groups),
        "main_case_rows": sum(g["main_case_rows"] for g in serializable_groups),
        "pending_case_rows": sum(g["pending_case_rows"] for g in serializable_groups),
        "ai_checked_case_rows": sum(g["ai_checked_case_rows"] for g in serializable_groups),
        "ai_checked_group_count": sum(1 for g in serializable_groups if g["has_ai_checked"]),
        "coverage_report_group_count": sum(1 for g in serializable_groups if g["has_coverage_report"]),
        "skipped_other_flow_artifacts": skipped_other_flows,
        "groups": serializable_groups,
    }
    return summary


def write_group_csv(path: Path, summary: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fields = [
        "project",
        "requirement_name",
        "dates",
        "artifact_count",
        "artifact_types",
        "main_case_rows",
        "pending_case_rows",
        "ai_checked_case_rows",
        "has_ai_checked",
        "has_coverage_report",
    ]
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        for group in summary["groups"]:
            row = {field: group[field] for field in fields}
            row["dates"] = ";".join(row["dates"])
            row["artifact_types"] = ";".join(row["artifact_types"])
            writer.writerow(row)


def print_summary(summary: dict[str, Any], print_paths: bool) -> None:
    print("# Requirement Testcase Artifact Index")
    print()
    for key in [
        "project_count",
        "group_count",
        "artifact_count",
        "main_case_rows",
        "pending_case_rows",
        "ai_checked_case_rows",
        "ai_checked_group_count",
        "coverage_report_group_count",
        "skipped_other_flow_artifacts",
    ]:
        print(f"- {key}: {summary[key]}")
    print()
    print("| Project | Requirement | Dates | Main | Pending | AI checked | Coverage |")
    print("|---|---|---:|---:|---:|---:|---|")
    for group in summary["groups"]:
        print(
            "| {project} | {requirement_name} | {dates} | {main} | {pending} | {ai} | {coverage} |".format(
                project=group["project"],
                requirement_name=group["requirement_name"],
                dates=", ".join(group["dates"]) or "-",
                main=group["main_case_rows"],
                pending=group["pending_case_rows"],
                ai=group["ai_checked_case_rows"],
                coverage="yes" if group["has_coverage_report"] else "no",
            )
        )
        if print_paths:
            for artifact in group["artifacts"]:
                print(f"  - {artifact['artifact_type']}: {artifact['path']}")


def main() -> int:
    args = parse_args()
    summary = build_index(args)
    if args.json:
        out = Path(args.json).expanduser().resolve()
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    if args.csv:
        write_group_csv(Path(args.csv).expanduser().resolve(), summary)
    print_summary(summary, args.print_paths)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
